title: ""
labels: []
body:
  - type: input
    id: link
    attributes:
      label: Link
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
